// Generated by training/envs/spot/to_onnx.py from checkpoint "misty-monkey-23". Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace spot_drivers::driver::policy_spec {

inline constexpr std::string_view onnx_file = "misty-monkey-23_spot.onnx";
inline constexpr std::string_view onnx_sha256 = "170ae91869e149265ef24dfc2d4565c711e00e7bcafb2d02d6395bad3b979aaf";
// Also stored inside the .onnx as metadata key "export_id"; compare at load.
inline constexpr std::string_view export_id = "b80e2880b392b3a4d84e49619cb53407";
inline constexpr double control_period_s = 0.02;
inline constexpr double control_rate_hz = 50;
inline constexpr std::array<float, 3> command_range = {1.5f, 1.0f, 1.2f};  // |vx|, |vy|, |yaw rate| limits
inline constexpr bool has_action_filter = false;

inline constexpr std::size_t num_leg_joints = 12;
inline constexpr std::size_t num_arm_joints = 7;
inline constexpr std::size_t num_joints = num_leg_joints + num_arm_joints;

// Tensors (names and sizes are checked once against the model at load).
inline constexpr std::string_view sensors_name = "sensors";
inline constexpr std::size_t sensors_size = 50;
inline constexpr std::string_view state_name = "state";
inline constexpr std::size_t state_size = 12;
inline constexpr std::string_view joint_position_targets_name = "joint_position_targets";
inline constexpr std::size_t joint_position_targets_size = num_joints;
inline constexpr std::string_view next_state_name = "next_state";
inline constexpr std::size_t next_state_size = state_size;

// All tensors are float32 with shape [1, size].
inline constexpr std::array<std::string_view, 2> input_names = {sensors_name, state_name};
inline constexpr std::array<std::size_t, 2> input_sizes = {sensors_size, state_size};
inline constexpr std::array<std::string_view, 2> output_names = {joint_position_targets_name, next_state_name};
inline constexpr std::array<std::size_t, 2> output_sizes = {joint_position_targets_size, next_state_size};

// Offsets into the sensors input and the state input/next_state output.
inline constexpr std::size_t sensors_base_linear_velocity_offset = 0;
inline constexpr std::size_t sensors_base_linear_velocity_size = 3;
inline constexpr std::size_t sensors_base_angular_velocity_offset = 3;
inline constexpr std::size_t sensors_base_angular_velocity_size = 3;
inline constexpr std::size_t sensors_projected_gravity_offset = 6;
inline constexpr std::size_t sensors_projected_gravity_size = 3;
inline constexpr std::size_t sensors_velocity_command_offset = 9;
inline constexpr std::size_t sensors_velocity_command_size = 3;
inline constexpr std::size_t sensors_joint_position_offset = 12;
inline constexpr std::size_t sensors_joint_position_size = 19;
inline constexpr std::size_t sensors_joint_velocity_offset = 31;
inline constexpr std::size_t sensors_joint_velocity_size = 19;

inline constexpr std::size_t state_previous_action_offset = 0;
inline constexpr std::size_t state_previous_action_size = 12;

// Joint order: 12 legs (FL, FR, RL, RR; hip, thigh, calf) then 7 arm.
inline constexpr std::array<float, 19> policy_default_pose = {0.0f, 1.04f, -1.8f, 0.0f, 1.04f, -1.8f, 0.0f, 1.04f, -1.8f, 0.0f, 1.04f, -1.8f, 0.0f, -3.141593f, 3.141593f, 1.570796f, 0.0f, -1.570796f, 0.0f};
inline constexpr std::array<float, 19> policy_kp = {60.0f, 34.0f, 152.0f, 60.0f, 34.0f, 152.0f, 60.0f, 34.0f, 152.0f, 60.0f, 34.0f, 152.0f, 1020.0f, 255.0f, 204.0f, 102.0f, 102.0f, 102.0f, 16.0f};
inline constexpr std::array<float, 19> policy_kv = {4.6f, 3.5f, 5.9f, 4.6f, 3.5f, 5.9f, 4.6f, 3.5f, 5.9f, 4.6f, 3.5f, 5.9f, 10.2f, 15.3f, 10.2f, 2.04f, 2.04f, 2.04f, 0.32f};

}  // namespace spot_drivers::driver::policy_spec
